extends: node-services
plugins: [html]

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  # Possible Errors
  # todo: use eslint-plugin-jsdoc instead of valid-jsdoc:
  # https://github.com/gajus/eslint-plugin-jsdoc/issues/14.
  # Note: Array.<type> syntax must be used instead of type[]:
  # https://github.com/eslint/eslint/issues/8376.
  valid-jsdoc: [1, {requireParamDescription: false, requireReturnDescription: false,
    preferType: {Boolean: boolean, Function: function, Null: undefined, Number: number,
      Object: object, String: string, Undefined: undefined, Void: void}}]

  # Best Practices
  no-else-return: 1
  no-floating-decimal: 0

  # Strict Mode
  strict: [1, never]

  # Stylistic Issues
  eol-last: [1, never]
  func-style: [2, expression]
  indent: [1, 2]
  quotes: [1, single, {avoidEscape: true}]
  semi: [1, never]
  require-jsdoc: [1, {require: {
    FunctionDeclaration: true,
    MethodDefinition: true,
    ClassDeclaration: true,
    ArrowFunctionExpression: true
  }}]
  no-extra-parens: 1
  no-cond-assign: [2, always]
  no-implicit-coercion: [1, {allow: ['!!']}]
  no-param-reassign: 1

  # ECMAScript 6
  arrow-body-style: 1
  arrow-parens: [1, as-needed]